version: '3.8'

services:
  mcpyoutube:
    image: guinness7777/mcp-replicate-solutia:lastest
    ports:
      - 3840:3840
    environment:
      - PORT=3840
    networks:
      - web
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager

networks:
  web:
    external: true
    name: dokploy-network